### ISSUE TITLE
Cannot run cfm --sync when another user is running cfm --livesync on the same server.

### ISSUE THREAD

**Issue by BlockArchitech** [supercrafter100/cubedfilemanager#33]
When one user tries to run cfm --sync, the user running cfm --livesync also runs cfm --sync while running cfm --linesync, causing an endless loop of reloading and saving, causing TPS to drop to 11.

More info:

Server version: 1.12.2
Client Version(s): 1.18.1
CFM version: latest

CFM LOG:
[*] Starting to download all scripts from the server...
[!] File "-spleef-old.sk" exists locally but not on the server! You may want to remove this file.
[!] File "-tab.sk" exists locally but not on the server! You may want to remove this file.
[!] File "collectibles.sk" exists locally but not on the server! You may want to remove this file.
[!] File "quests.sk" exists locally but not on the server! You may want to remove this file.
[!] File "scoreboard.sk" exists locally but not on the server! You may want to remove this file.
^ cfm --sync side

@zNotChill was the user running CFM --livesync

**Comment by BlockArchitech** [comment]
Forgot to add, I'm on a MacBook pro (2017, 4TBT3) with macOS Monterey 12.1

**Comment by PondWader** [comment]
Theoretically, this should not be possible as no connection is made to the live sync server during syncing. What I think is happening is that you (the person running sync) is running multiple instances of CubedFileManager. One which is connected to livesync and therefore uploading all the events. It is very much advisable to only ever run one instance of CFM on your computer for consistency and reliability.

Please let me know if this is not the case.

**Comment by BlockArchitech** [comment]
I didn't have another active instance open at the time, but prior it failed twice to open a websocket with the error code -2

**Comment by supercrafter100** [comment]
Yeah I noticed. I pushed a fix for that issue. Let me know if this happens again

**Comment by BlockArchitech** [comment]
Awesome! I'll get this updated.

(closing issue)
