### ISSUE TITLE
TypeError when trying to list servers

### ISSUE THREAD

**Issue by BlockArchitech** [supercrafter100/cubedfilemanager#36]
When cfm tries to list servers, a TypeError is thrown.

`TypeError: Cannot read properties of undefined (reading 'split')`

```
[!] Please note: this fix is far from perfect and issues could still occur.
 Please enter the "cf_clearance" cookie: cookie
 Please enter your browser user-agent (you can find this at https://www.whatismybrowser.com/detect/what-is-my-user-agent/): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
[✓] Logged in as gibbiemonster
/home/home/.nvm/versions/node/v16.16.0/lib/node_modules/cubedfilemanager/dist/lib/RequestsManager.js:730
                                        id = parseInt(hrefs[i].split('?s=')[1]);
                                                               ^
```

No idea if it matters, but I use node version manager.

System info:

Debian 11
node v16.16.0
npm v8.11.0
shell: zsh

**Comment by supercrafter100** [comment]
We've disabled under attack mode for the playerservers website. The cloudflare bypass system is very sketchy and I'm not the one who made it. CFM should be back to working though

**Comment by supercrafter100** [comment]
Actually there may be a different issue. I'll do some investigating

**Comment by supercrafter100** [comment]
Please downloading the latest version of cfm. This is version `3.1.3` and has been released on npm so it should be available if you download it via your package manager. This should resolve the issue.

**Comment by BlockArchitech** [comment]
Seems to be working!
