### ISSUE TITLE
Failed to log in

### ISSUE THREAD

**Issue by zNotChill** [supercrafter100/cubedfilemanager#40]
I believe this has something to do with the new **sudden** update to the website (which looks horrible)

```
[*] Writing to credentials storage
[✓] Credentials storage successfully saved
[x] Failed to log in as zNotChill
```

**Comment by supercrafter100** [comment]
The html changed, breaking the login system. I'll try me best to fix it asap

**Comment by zNotChill** [comment]
broken again :(

Another stupid website change I assume
```
 id = parseInt(hrefs[i].split('?s=')[1]);
                                                               ^

TypeError: Cannot read properties of undefined (reading 'split')```

**Comment by supercrafter100** [comment]
ffs

**Comment by zNotChill** [comment]
yep broken again, probably something to do with the new table

**Comment by zNotChill** [comment]
I think I fixed it, by just changing 
```$('tr > td:nth-child(5) > a').each(function (index, element) {```
to ```$('tr > td:nth-child(6) > a').each(function (index, element) {```

**Comment by supercrafter100** [comment]
Usually it’s easy fixes yeah
