### ISSUE TITLE
Issue: CFM doesnt save into a folder already made named the same thing

### ISSUE THREAD

**Issue by polyknox** [supercrafter100/cubedfilemanager#47]
![Capture](https://github.com/supercrafter100/cubedfilemanager/assets/147343741/8fe1c695-610b-46a3-947b-06c0dd17baf7)
![Capture](https://github.com/supercrafter100/cubedfilemanager/assets/147343741/c50607ee-b652-460f-8f1d-40302ee8eeb1)
This is an issue as most people store stuff in folders so stuff is easier to find

**Comment by blockarchitech** [comment]
Folders work perfectly fine for me. Judging by screenshot two, your skript is empty and looking at the folders you definitely have skripts in them so running cfm --sync would probably fix most your issues
