### ISSUE TITLE
Support for folders

### ISSUE THREAD

**Issue by DebitCardz** [supercrafter100/cubedfilemanager#5]
I feel as if there should be support for folders in CFM, For example if in my codebase I have it structured as such -
Core/whatever then CFM should make the folder Core and then put whatever.sk in that folder.

**Comment by supercrafter100** [comment]
hm not a bad idea. Ill see what I can do in the next update. Altough I dont know how it would work with already existing folders 🤷‍♂️

**Comment by DebitCardz** [comment]
hurry up and do it

**Comment by DebitCardz** [comment]
do it

**Comment by supercrafter100** [comment]
I will add this feature in the next update

**Comment by supercrafter100** [comment]
Folder support has been added. Use the --foldersupport ( --fs ) flag to enable it

**Comment by DebitCardz** [comment]
do it but better this time

**Comment by supercrafter100** [comment]
It has been added. Im closing the issue
